//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff_tbl
    {
       [Key]
        public int StaffId { get; set; }
        public string Staffname { get; set; }
        public string Staffphone { get; set; }
        public string Gender { get; set; }
        public string Staffpassword { get; set; }
    }
}
